id: P0FB8A088
initial_creation_type: input
source_metadata:
  title: Jonang Series
  language: en
  description: 'Texts related to the Jonang (jo nang) School of Tibetan Buddhism:'
  volume:
    1bb150abc9b543df8867d9629a2a5593:
      title: Aspiration Prayer for the Flourishing of the Jonang Teachings
      parent: Aspiration Prayers
created_at: '2022-03-01T04:00:58.716534'
last_modified_at: '2022-03-01T04:00:58.716540'
